### ISSUE TITLE
Cannot use US Standard region

### ISSUE THREAD

**Issue by jseppi** [fhemberger/catbox-s3#3]
For buckets created in the AWS US Standard region, the URLs to objects will be of the form `https://s3.amazonaws.com/...`

The requirement to specify a region (or default to eu-west-1) prevents this module from being able to use US Standard region buckets.

**Comment by jseppi** [comment]
Perhaps it would be easiest to just use the S3 `client.getObject` method instead of manually constructing a GET request

**Comment by fhemberger** [comment]
Hmm, I thought specifying `us-east-1` should be enough for that … I'll change that.
For retrieval, I decided to use direct GET requests for performance reasons.

**Comment by jseppi** [comment]
Great, thanks!

**Comment by fhemberger** [comment]
I've updated the current master, can you please check it? If everything works as expected, I'll push it as v1.0

**Comment by jseppi** [comment]
Confirmed that it now works with US Standard. Thanks! :+1:

**Comment by fhemberger** [comment]
Closed by 434f08b54a638314fc6c4c3be080b615f7bb9b99.
