### ISSUE TITLE
Library does not function with latest version of Catbox

### ISSUE THREAD

**Issue by SpaceMacGyver** [fhemberger/catbox-s3#54]
Catbox has apparently made the decision to [force users into async/await](https://github.com/hapijs/catbox/pull/190).  This library assumes a callback pattern and for me is failing in `internals.Connection.prototype.start` due to a callback no longer being provided:

![image](https://user-images.githubusercontent.com/2105094/32550995-b111ece4-c454-11e7-86cc-31914c64e7ca.png)

One level up the stack, in [**catbox/lib/client.js**](https://github.com/hapijs/catbox/blob/master/lib/client.js#L35):

![image](https://user-images.githubusercontent.com/2105094/32551050-d94fdab8-c454-11e7-92bd-bd30a5ca74e4.png)

**Comment by fhemberger** [comment]
Thanks for reporting this. I'm aware of the latest changes in catbox, but didn't have the time yet to update catbox-s3.

Help/PR welcome!

**Comment by fhemberger** [comment]
Fixed in `v4.0.0`, thanks @ScottyFillups!
